// <auto-generated />
using System;
using IntegrationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607130837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrationService.Models.AlertHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DeviationPercent")
                        .HasColumnType("float");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxNormal")
                        .HasColumnType("float");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MinNormal")
                        .HasColumnType("float");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SentAt");

                    b.ToTable("AlertHistories");
                });

            modelBuilder.Entity("IntegrationService.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertSent")
                        .HasColumnType("bit");

                    b.Property<double?>("DeviationPercent")
                        .HasColumnType("float");

                    b.Property<bool>("IsOutOfRange")
                        .HasColumnType("bit");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDbId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserDbId");

                    b.HasIndex("UserId", "MetricType");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("IntegrationService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IntegrationService.Models.UserNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserDbId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserDbId");

                    b.HasIndex("UserId", "MetricType")
                        .IsUnique();

                    b.ToTable("UserNorms");
                });

            modelBuilder.Entity("IntegrationService.Models.Measurement", b =>
                {
                    b.HasOne("IntegrationService.Models.User", "User")
                        .WithMany("Measurements")
                        .HasForeignKey("UserDbId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntegrationService.Models.UserNorm", b =>
                {
                    b.HasOne("IntegrationService.Models.User", "User")
                        .WithMany("UserNorms")
                        .HasForeignKey("UserDbId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntegrationService.Models.User", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("UserNorms");
                });
#pragma warning restore 612, 618
        }
    }
}
